---
- name: Update Packages
  hosts: proxmoxnodes  # Replace with your target hosts or inventory group
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
