---
- name: Upgrade Packages
  hosts: dockerhosts  # Replace with your target hosts or inventory group
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Upgrade all packages
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes
